### ISSUE TITLE
Switch to cargo zigbuild for Linux releases

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#1055]
We've been resorting to increasingly convoluted workarounds to get nextest compiling against glibc 2.27. So far we have:

* Use an ubuntu 18.04 container as defined in https://github.com/nextest-rs/docker/tree/main/ubuntu-18.04
* Pin actions/checkout to v3 since v4 pulls in node 20, which needs glibc 2.28.

The list of hacks is only going to grow, but we are ultimately limited by the fact that we need to support at least glibc 2.28 (minimum of versions supported across CentOS, Debian, and Ubuntu LTS).

It seems like cargo zigbuild might be able to solve our problems here by letting us build against glibc 2.27 (or 2.28?), and I did a basic check (`strings target/release/cargo-nextest | grep GLIBC`) to ensure it works. Some notes:

* The docker container at https://hub.docker.com/r/messense/cargo-zigbuild has rustc 1.70 which is a bit outdated. I think we should manage the Rust version ourselves.
* https://github.com/taiki-e/upload-rust-binary-action supports `cargo zigbuild` and is likely our best bet.

ccing @NobodyXu in case you have thoughts.

**Comment by NobodyXu** [comment]
We use cargo-zigbuild with cargo-auditable and cargo-hack (<=0.6.10, newer version use new cargo subcommand which cargo-zigbuild doesn't support forwarding yet https://github.com/rust-cross/cargo-zigbuild/issues/195) by setting env CARGO

https://github.com/cargo-bins/cargo-binstall/blob/dc20cb7eb37d0bc4b498ade18a4e78a52358c6ad/justfile#L46

**Comment by sunshowers** [comment]
Fixed in commits leading up to https://github.com/nextest-rs/nextest/commit/d80d85fbfa3dce4e22330a8fff2b31c95826fee7. Verified that this worked in an Ubuntu 18.04 container:

```
root@5ab2a8b65fd0:/# curl -fsSL https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-0.9.62-a.2/cargo-nextest-0.9.62-a.2-x86_64-unknown-linux-gnu.tar.gz | tar zx
root@5ab2a8b65fd0:/# ./cargo-nextest
```
