### ISSUE TITLE
Support units string for terminate-after

### ISSUE THREAD

**Issue by vlovich** [nextest-rs/nextest#1066]
Most of the timeout configurations support specifying a sub-minute number of seconds. However, terminate-after only supports an integer number of minutes. It would be nice if terminate-after could be configured to terminate if a test has taken more than (for example) 15 seconds. Alternatively, instead of an explicit terminate-after, maybe "slow" tests should automatically trigger the terminate after logic. That way you only have "slow" and "grace period". Not sure what the purpose of "slow" is intended to communicate if the test isn't getting terminated.

**Comment by sunshowers** [comment]
Thanks for the report!

terminate-after actually takes a number of slow-timeout periods. The slow-timeout period is is 60 seconds by default, but can be set to any duration.

It is often useful to know which tests are slow (e.g. while looking for test bottlenecks) but not terminate them.

**Comment by sunshowers** [comment]
https://nexte.st/book/slow-tests.html#terminating-tests-after-a-timeout This is documented here.

**Comment by vlovich** [comment]
Oh wow. I totally misread the docs. Thanks for the correction!

**Comment by sunshowers** [comment]
Np, I edited the docs a bit because it wasn't clear.
