### ISSUE TITLE
An option to fail if no test has been actually run

### ISSUE THREAD

**Issue by dpc** [nextest-rs/nextest#1107]
I just noticed that our CI has actually not been running certain tests suites for some weird reason, and just skipping all tests in them:

```
00:00:30     Starting 0 tests across 50 binaries (18 skipped)
00:00:30 ------------
00:00:30      Summary [   0.000s] 0 tests run: 0 passed, 18 skipped
```

The reason is described #1108, but irrespective of it I wish there was an option to just prevent that from ever happening again. If no tests were run that I'd say that the whole invocation was a failure. It could be a opt-in or opt-out behavior, but would be great to have it.

**Comment by sunshowers** [comment]
I think in CI (though not in local runs), it is ~always a bug to run 0 tests. We should:

* always produce a warning if no tests are run
* in CI, eventually error with a special exit code if no tests are run.

We should consider making a change via the [behavior change process](https://nexte.st/book/stability.html#making-behavior-changes) to enable this.

**Comment by dpc** [comment]
> I think in CI (though not in local runs),

Is there a standard way to tell `cargo-nextest` that it's running in the CI? I wasn't aware of it.

It seems to me that in local development it doesn't matter all that much if invocation of `cargo-nextest` returns an error message "no tests to run" and error exit code. If that was the intention, developer will just ignore it.

Defaulting to erroring keeps the behavior unified, and might even prevent silly local dev. mistakes where the user doesn't notice a typo and the fact that no test was actually being run.

**Comment by sunshowers** [comment]
> Is there a standard way to tell cargo-nextest that it's running in the CI? I wasn't aware of it.

Yes, we already use [`is_ci`](https://crates.io/crates/is_ci) for this purpose.

> It seems to me that in local development it doesn't matter all that much if invocation of cargo-nextest returns an error message "no tests to run" and error exit code. If that was the intention, developer will just ignore it.

I think that actually makes sense: we have to be careful not to produce an ugly error in this case, but we can exit with a special non-zero exit code.

**Comment by sunshowers** [comment]
This is now going to be implemented as part of this behavior change: https://github.com/nextest-rs/nextest/discussions/1646. Closing in favor of that, thanks!
