### ISSUE TITLE
Possibility of running multiple tests in one batch

### ISSUE THREAD

**Issue by tabokie** [nextest-rs/nextest#1127]
Hi, I remember nextest spawns child processes to run test cases one at a time (haven't checked the latest code, correct me if wrong). The performance overhead could be small for normal tests, but for async tests (such as `#[tokio::test]`), multiple cases cannot parallelize in this runner model.

I wonder if it's possible to run multiple test cases within one process? For example fetching small batches of cases from the job queue to execute.

**Comment by sunshowers** [comment]
Hi,

This is #27 and as listed there is a very large endeavor, especially to make work with all of nextest's features. However, in general Tokio is super quick to start up so I'm surprised this is a major issue.

**Comment by sunshowers** [comment]
Going to close this as a dup of #27, thanks for the report!

**Comment by tabokie** [comment]
Oh, good to know. To clarify though, the issue is not tokio startup time. It's the parallelism between multiple test cases. When running async tests with cargo-test, multiple tests can run at the same time even if user specifies job=1.

**Comment by sunshowers** [comment]
Huh, I'd never heard of that. I'd consider that a bug to be honest.

**Comment by sunshowers** [comment]
Oh is this because -j1 controls build jobs for cargo test and test jobs for nextest?

**Comment by tabokie** [comment]
Ach, looks like it. Used the wrong command when testing this before..
