### ISSUE TITLE
Help filtering test target

### ISSUE THREAD

**Issue by tabokie** [nextest-rs/nextest#1129]
I have a module of tests specified as a test target, but I'm not able to filter them using:
- `-E 'package(target_name)'`
- `-E 'test(target_name)'`
- `-E 'package(package_name::target_name)'` (complains 'no packages matched this')
- `-E '/package_name::target_name/'` (complains 'missing expression', 'unparsed input')

Tree:
```
tests/integration
├── basic
│   ├── mod.rs
│   └── test_write.rs
├── Cargo.toml
└── replication
    ├── mod.rs
```
tests/integration/Cargo.toml:
```
[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[[test]]
name = "basic"
path = "basic/mod.rs"

[[test]]
name = "replication"
path = "replication/mod.rs"
```
nextest list:
```
cargo nextest list -p integration    
    Finished test [unoptimized + debuginfo] target(s) in 0.31s
integration::basic:
    ...
integration::replication:
    test_cluster::test_cluster
    ...
```

**Comment by sunshowers** [comment]
What you need to say today is `-E 'package(integration) & binary(basic)'`. But I'm not satisfied with this so in the next version there's going to be a `binary_id` predicate.
