### ISSUE TITLE
nextest run does not inherit `OUT_DIR` env var from Cargo

### ISSUE THREAD

**Issue by ShiqiHe000** [nextest-rs/nextest#1140]
Hello! I'm using `cargo-nextest-nextest 0.9.63`. I'm testing on a package `my_package`, which has the structure:
```
my_package/
|-- Cargo.toml
|-- LICENSE
|-- README
|-- build.rs
|-- src
|   |-- bin
|   |   `-- test_executable.rs
|   |-- errors.rs
|   `-- lib.rs
`-- tests
    |-- test.rs
```

In the `test.rs` file, I need to use `OUT_DIR` env var. I ran the test with `cargo nextest run -p my_package` and it failed at this statement:
```
env::var("OUT_DIR").unwrap()
```
since the `OUT_DIR` env var is not set. 

The test can pass if I run it with `cargo test -p my_package`. I checked `OUT_DIR` was set to the package's path.  

The test can pass if I run `OUT_DIR=<dir> cargo nextest run -p my_package`. So in this case, I suspect that nextest does not inherit the [ OUT_DIR env vars](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads) from Cargo. 

Please let me know if this is a bug thank you!

**Comment by sunshowers** [comment]
Huh interesting, I didn't realize `OUT_DIR` was set at runtime if a build script is present. Definitely a bug in nextest, let me see what a fix might look like.

**Comment by sunshowers** [comment]
I hope to release #1147 some time at the end of the week. Could you give it a go?

```
cargo install --locked --git https://github.com/nextest-rs/nextest cargo-nextest
```

**Comment by ShiqiHe000** [comment]
I tested! It works! Thank you so much~
