### ISSUE TITLE
Unexpected behavior when custom test harnesses don't parse arguments

### ISSUE THREAD

**Issue by indygreg** [nextest-rs/nextest#122]
Foremost, thank you for this project! It is saving me a lot of time in my core dev workflow.

As part of porting a monorepo to support this project, I encountered some friction around custom test harnesses that I thought worth reporting.

I'm using version 0.9.11.

https://nexte.st/book/custom-test-harnesses.html says that custom test harnesses `MUST` support being run with `--list --format terse` and a few other argument patterns. That's all fair. Price you pay for admission I suppose.

However, what tripped me up was how the current behavior of `nextest list` and `nextest run` can apparently **silently ignore** non-conformance in certain scenarios.

I have a few custom tests declared with `[[test]] harness = false` that are literally a simple executable with `fn main()` that exits 0 on success or non-0 on failure. No test harness whatsoever. No argument parsing to be found. e.g. https://github.com/indygreg/PyOxidizer/blob/75d63db88d4e4823a94480b4dfa7750bf190ec74/pyoxy/tests/yaml.rs

Maybe I'm not abiding by best practices when it comes to using `harness = false`. However, `cargo test` runs these tests/executables just fine.

However, with `nextest list` and `nextest run`, these `harness = false` executables are effectively ignored, often silently.

I think the problem stems from `nextest list` not being able to discover tests since the test executable doesn't implement `--list --format terse`. Since output for this invocation is the actual test output and not the expected test list output, nextest assumes the test list is empty.

I suspect many people don't hit this because they are using actual custom test harnesses with command argument parsing and those get tripped up on unknown arguments. Since my binaries don't even look at `argv`, `--list --format terse` invocations just run the actual test!

Some questions / areas for potential improvement:

* Should `nextest` complain when stdout from `--list format terse` invocations doesn't conform to the `my-test-1: test` syntax? The docs clearly say `Other output MUST NOT be written to stdout.`
* If `nextest` complains, should this be a warning or fatal error? If configurable, should there be CLI flags to control behavior?
* Should there be some kind of special output from test harnesses to indicate *no tests* or *skip* support? My thinking here is `nextest` might want to receive positive confirmation from a test harness that it is aware of the custom arguments nextest is passing in. If an executable can't demonstrate that it is *nextest aware*, nextest might want to do something special with that knowledge, like tell the user their custom test harness doesn't support nextest. This would be actionable information for project developers.
* What do you think about the idea of a simple crate for enabling test executables to implement handling of arguments like `--list --format terse`? This isn't the hardest thing to implement in my custom tests (especially when there is a single test in each binary). But if there were a crate where I could easily register named tests and that also handled argument parsing and test dispatch, this is something I'd probably use since I don't want to have to think about implementation details of the CLI arguments protocol.

Thanks again for this terrific project. Even with the custom harness quirks, it is still light years ahead of my old workflow.

**Comment by indygreg** [comment]
So, uh, I failed to realize that arguments like `--list` and `--format terse` are also part of the contract that Cargo's test runner imposes. Makes sense and obvious in hindsight. (I somehow got the notion that nextest was altering compiled test binaries somehow to make them compatible with nextest's runner.)

I further see that crates like https://crates.io/crates/libtest-mimic already exist to enable implementing this test harness interface (without having to pull in all of `libtest`).

Perhaps the nextest docs should recommend that `harness = false` tests should use an existing minimal harness such as `libtest-mimic`?

**Comment by sunshowers** [comment]
Hi Greg! Hope you're doing well.

> [nexte.st/book/custom-test-harnesses.html](https://nexte.st/book/custom-test-harnesses.html) says that custom test harnesses MUST support being run with --list --format terse and a few other argument patterns. That's all fair. Price you pay for admission I suppose.

Yes this is true. Note that contrary to your reply, this is not *required* by the standard `cargo test` runner -- that only cares about the exit code. [How nextest works](https://nexte.st/book/how-it-works.html) covers this in more detail.

> However, with nextest list and nextest run, these harness = false executables are effectively ignored, often silently.

Hmm, the test list phase done by both `nextest list` and `nextest run` will fail loudly if your harness exits with a non-zero code. It won't be pretty, but it won't be silent either.

> I suspect many people don't hit this because they are using actual custom test harnesses with command argument parsing and those get tripped up on unknown arguments.

I don't have any stats to back it but my general impression is that custom test harnesses are pretty uncommon. Lots of people have tried nextest already and very few people have complained about this.

> Should nextest complain when stdout from --list format terse invocations doesn't conform to the my-test-1: test syntax? The docs clearly say Other output MUST NOT be written to stdout.

Nextest already does that, and makes it a fatal error. However, not printing out any lines at all is not considered an error (see below).

> Should there be some kind of special output from test harnesses to indicate no tests or skip support? My thinking here is nextest might want to receive positive confirmation from a test harness that it is aware of the custom arguments nextest is passing in. If an executable can't demonstrate that it is nextest aware, nextest might want to do something special with that knowledge, like tell the user their custom test harness doesn't support nextest. This would be actionable information for project developers.

Hmm, the problem with this is that the default test runner can also produce no output if it wants to indicate that there are no tests within it.

> What do you think about the idea of a simple crate for enabling test executables to implement handling of arguments like --list --format terse? This isn't the hardest thing to implement in my custom tests (especially when there is a single test in each binary). But if there were a crate where I could easily register named tests and that also handled argument parsing and test dispatch, this is something I'd probably use since I don't want to have to think about implementation details of the CLI arguments protocol.

That's `libtest-mimic` as you pointed out -- #38 covers that. I haven't had the chance to see how well it works but I'd be curious to hear about it!

> (I somehow got the notion that nextest was altering compiled test binaries somehow to make them compatible with nextest's runner.)

No, nextest just runs `cargo test --no-run` with zero customizations. In fact it goes out of its way to not do any customizations so that existing `cargo test` builds can be reused without causing cache invalidation issues.

**Comment by sunshowers** [comment]
I'm going to close this issue since I don't really see a way for nextest to do better. Let's fix up libtest-mimic to work with nextest in #38.
