### ISSUE TITLE
Running `nextest` on `nightly` errors with `unknown package ID`

### ISSUE THREAD

**Issue by YaronWittenstein** [nextest-rs/nextest#1350]
### How to reproduce the bug?

`cargo +nightly nextest run --no-fail-fast --workspace --release`

**Errors with**

```txt
Error: 
   0: error querying package graph
   1: unknown package ID: PRIVATE_PACKAGE_NAME
```

**However, running the same command on Stable Rust works perfectly well:**
`cargo +stable nextest run --no-fail-fast --workspace --release`

It seems that the error has nothing to do with the test running themselves.
I get the same error message when doing: `cargo +nightly nextest list` (while `cargo +stable nextest list` works)

**Comment by sunshowers** [comment]
You may have to update your nightly -- please see #1232.

**Comment by sunshowers** [comment]
Going to close this -- please reopen if you still run into this afterwards. Thanks.
