### ISSUE TITLE
Ability to specify a custom cargo profile?

### ISSUE THREAD

**Issue by vlovich** [nextest-rs/nextest#1380]
Terminology gets confusing due to nextest profiles being different from cargo profiles & thus hard to search, but basically would be nice to have a way to pass through a specific cargo profile name to test with instead of just `--release` (e.g. I have a custom cargo profile I want to build and run the tests with). If this is available, I haven't been able to find it.

**Comment by sunshowers** [comment]
--cargo-profile should work!

**Comment by vlovich** [comment]
Oh nice.
