### ISSUE TITLE
`build.rs` line change slows tests

### ISSUE THREAD

**Issue by cloudhead** [nextest-rs/nextest#1397]
The following line in my build.rs makes nextest take 100s+ instead of 12s:

```
    println!("cargo::rerun-if-changed=.git/HEAD");
```

This is on rust 1.77. When I was on 1.74, the line looked like this, and didn't have an effect on test speed:

```
    println!("cargo:rustc-rerun-if-changed=.git/HEAD");
```

If I remove the line, tests are fast again. Worth noting that `cargo test --all` is not affected by this.

**Comment by sunshowers** [comment]
Thanks for the report! Do you have a minimal repro or example somewhere?

**Comment by cloudhead** [comment]
I'm not experiencing this anymore and I forgot how I resolved it, sorry! Closing.
