### ISSUE TITLE
Add a way to escape `/` in regexes

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#144]
While testing out expression filtering, I noticed that there's currently no way to escape a `/` in a regex. Ideally we'd support this via a `\/` sequence.

cc @Guiguiprim, what's the best way to handle this in your opinion?

**Comment by Guiguiprim** [comment]
I guess in a way similar to how unicode string are parsed.

**Comment by Guiguiprim** [comment]
That is exactly what I was thinking of. I'm going to have a try at it.


Speaking of escaping I realize that the unicode parsing (that I took from `nom` examples) also support escaping whitespaces, aka:

```
"test(d\
d)
```

is equivalent to

```
test(dd)
```

I'm not sure if we should keep it or how to document it.

More generally, I wonder if I shouldn't have simplified it a bit more...

**Comment by sunshowers** [comment]
Ah yeah I was looking at that. Not really worth keeping I think. We can always add it later if there's demand.

**Comment by sunshowers** [comment]
Done in #146, thanks!
