### ISSUE TITLE
Add support for `cargo test`s --skip and --exact command line flags

### ISSUE THREAD

**Issue by svix-jplatte** [nextest-rs/nextest#1483]
Hi, I was just looking for an issue about `--skip` in nextest and found #29 which is saying that these are supported, but using different syntax. This is problematic for my use case since I have a test script that runs `cargo nextest run` if available, but falls back to regular `cargo test` if nextest is not installed. I also think that for interactive usage, `--skip` and `--exact` are much easier to use than the filter expression syntax.

Would you consider adding support for these flags? The implementation could just instantiate the appropriate filter expressions internally, so it should be really simple.

**Comment by sunshowers** [comment]
Hi -- I was hesitant to add this at first, but over the last few months I've changed my mind. I'm happy to accept a PR for this. Some notes:

* `--skip` and `--exact` should only be accepted after `cargo nextest run --` -- the point after `--` is where we accept test binary args. See https://github.com/nextest-rs/nextest/blob/02a0cf0cb7d388c4cb709b2c9612a0b2b6bda800/cargo-nextest/src/dispatch.rs#L606-L629.
* Just like the existing support, filter expressions must be ANDed with them. i.e. if both a filter expression and `--skip`/`--exact` is passed in, both should be matched for a test to be run.
* I'm not exactly sure of the semantics of `--skip` and `--exact` especially when they're passed in together, so a full description of the semantics, with tests would be wonderful.

**Comment by svix-jplatte** [comment]
I was able to get it to work, see #1653. It's in draft state though because I broke a test and couldn't really figure out how to add a new one either. And it's quite likely I didn't solve it in the best possible way.

**Comment by sunshowers** [comment]
Released as part of cargo-nextest 0.9.80, which will be out within the next 15-20 minutes. Thanks again for your hard work!

**Comment by sunshowers** [comment]
Also added documentation: https://nexte.st/docs/running/#--skip-and---exact

**Comment by svix-jplatte** [comment]
Thanks!
