### ISSUE TITLE
Fail tests that leak pipes

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#15]
It is possible to write a test that ends up leaking a pipe (e.g. creates a process but doesn't terminate it). Currently, the test runner hangs on encountering such a test.

Instead, we should figure out a way to:
* detect such a situation (a small amount of raciness between waiting on process exit and checking that the handles are closed is fine)
* mark such a test as failure with a `LEAK` message or similar

**Comment by brkydnc** [comment]
Hi, could you please give an example piece of code that causes this behavior? This is for understanding the problem better. Thanks in advance.

**Comment by Bauxitedev** [comment]
I've run into this issue as well. Strangely enough, passing `--no-capture` to Nextest causes the tests to run normally. But if I remove the flag, the tests hang forever.

**Comment by sunshowers** [comment]
Thanks for the further report. I agree that this should be a priority to fix given that even terminate-after isn't enough. Will look into it really soon.

**Comment by sunshowers** [comment]
I started playing around with how to do this -- it involves switching to an async executor so that we can select on timeouts and pipe reads at the same time, which I'm doing in #359.

**Comment by sunshowers** [comment]
@Bauxitedev this is now out as part of cargo-nextest 0.9.27.
