### ISSUE TITLE
Handle commas in filter expressions

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#153]
We should leave open commas as an extension point for further arguments. This means rejecting commas in name matchers with unary set operators for now, and adding `\,` as an escape (doesn't need to be done within a regex context).

This probably blocks the full release so filing this to track this issue.

cc @Guiguiprim if you're interested in solving this.

**Comment by Guiguiprim** [comment]
I will have a look at it. Should be simple enough.
