### ISSUE TITLE
Default package filtering to exact while keeping default test filtering as contains

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#155]
Having used filter expressions for a bit -- generally, most users expect package filtering to be based exactly on the package name, and test filtering to match on part of the test name. So default to these while allowing users to change them with the matchers that already exist.

This blocks the full release of filter expressions.

cc @Guiguiprim (sorry for ccing you to these, lmk if I should stop!)

**Comment by Guiguiprim** [comment]
Oh... That feels indeed the right move.

I will look at it also.

I'm happy to help you finish properly this feature ! (You already did a nice job at cleaning it up 🙂)

**Comment by sunshowers** [comment]
Fixed in #156.
