### ISSUE TITLE
Basic test name filters and filter expressions should be ORed

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#160]
If you specify `cargo nextest run test1 -E 'test(test2)'`, all tests containing either `test1` or `test2` should be run.

cc @Guiguiprim

**Comment by Guiguiprim** [comment]
That's indeed a bug, should be simple enough to fix.
Will do

**Comment by Guiguiprim** [comment]
That's indeed a bug, should be simple enough to fix.
Will do

**Comment by sunshowers** [comment]
BTW we decided to go back to `AND` semantics in 4cd2788db5ede827dd98fd01d3ce7ec6de1698da -- see the reasoning in the commit for why.
