### ISSUE TITLE
I encountered a bug, installation error

### ISSUE THREAD

**Issue by sensuigit** [nextest-rs/nextest#1611]
I am not sure about the specific reason, but after testing, I tried to install the 0.9.72 error and the error message is as follows Later, I tried version 0.9.70 again, but it still failed. In the end, I successfully tried version 0.9.60 The specific reason is unknown. I am not sure if it is a bug or an issue with my own environment

my environment:
WINDOWS 11 
RUST rustc 1.80.0 (051478957 2024-07-21)

rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

 stable-x86_64-pc-windows-gnu unchanged - rustc 1.80.0 (051478957 2024-07-21)
 stable-x86_64-pc-windows-msvc unchanged - rustc 1.80.0 (051478957 2024-07-21)

-----------------------------------------------------------------------------------------------------------
`          Warning: .drectve `-exclude-symbols:"anon.b0c9924d77b52bffdec93a214761cbe3.1.llvm.3270928078830944216" ' unrecognized
          Warning: .drectve `-exclude-symbols:"anon.b0c9924d77b52bffdec93a214761cbe3.2.llvm.3270928078830944216" ' unrecognized
          Warning: .drectve `-exclude-symbols:"anon.b0c9924d77b52bffdec93a214761cbe3.4.llvm.3270928078830944216" ' unrecognized
          Warning: .drectve `-exclude-symbols:"anon.b0c9924d77b52bffdec93a214761cbe3.5.llvm.3270928078830944216" ' unrecognized
          Warning: .drectve `-exclude-symbols:"anon.b0c9924d77b52bffdec93a214761cbe3.6.llvm.3270928078830944216" ' unrecognized
          Warning: corrupt .drectve at end of def file
          Warning: .drectve `-exclude-symbols:_ZN3std9panicking11begin_panic17h00e8c402b736a98cE ' unrecognized
          Warning: .drectve `-exclude-symbols:"_ZN42_$LT$$RF$T$u20$as$u20$core..fmt..Debug$GT$3fmt17hbca840e55c15f6afE" ' unrecognized
          Warning: .drectve `-exclude-symbols:"_ZN44_$LT$$RF$T$u20$as$u20$core..fmt..Display$GT$3fmt17h3025113de0e0d956E" ' unrecognized
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          collect2.exe: error: ld returned 5 exit status

error: could not compile `cargo-nextest` (bin "cargo-nextest") due to 1 previous error
error: failed to compile `cargo-nextest v0.9.72`, intermediate artifacts can be found at `C:\Users\SXXX\AppData\Local\Temp\cargo-installRV0I8n`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.`

**Comment by sunshowers** [comment]
Thanks for the report! To be honest I've never seen this before, this looks like corruption in your build workflow.

I apologize but I have to ask: do you have a 13th or 14th gen Intel desktop chip? https://www.pcworld.com/article/2415697/intels-crashing-13th-14th-gen-cpu-nightmare-explained.html

**Comment by sunshowers** [comment]
You're also welcome to install the prebuilt binaries: https://nexte.st/docs/installation/pre-built-binaries/#windows-x86_64

**Comment by sensuigit** [comment]
I don't have 13th or 14th gen Intel . My CPU is E2680v4 * 2  64 core, which is a workstation CPU Perhaps it's related to the CPU?

**Comment by sunshowers** [comment]
Maybe, I'm not sure!

You can try doing a git bisect on this repo to see if any particular commit here is to blame. You can start by marking the tag `cargo-nextest-0.9.60` as good and `cargo-nextest-0.9.72` as bad.

**Comment by sunshowers** [comment]
Going to close this since this doesn't appear to be a nextest issue. If the bisect suggests otherwise please feel free to report this.
