### ISSUE TITLE
capture stack backtrace of all threads in a test?

### ISSUE THREAD

**Issue by keepsimple1** [nextest-rs/nextest#1696]
Using `nextest`, with RUST_BACKTRACE=1,  is it possible to capture the stack backtraces of all threads in a test?  i.e. not only the thread that panicked. 

Sample pseudo code in a test:
```rust
    fn test_operation_timeout() {
        let _ = std::thread::spawn(|| {
            println!("new thread to run operations:");
            operations();
        });

        sleep(Duration::from_millis(200));
        if handler.is_finished() {
            println!("succcess! we are done.")
        } else {
            panic!("operations taking too long!");
        }
    }
```
When the above test fails due to timeout, it prints the stack backtrace of the panic thread by default.  Is it possible to obtain the backtrace of the `operations` thread as well?  Thanks!

**Comment by sunshowers** [comment]
Thanks for the question! No, as things currently stand nextest is not really aware of processes' internal working like that. Panics within tests are handled entirely within the test -- there is no runtime that nextest injects into the test, if that makes sense.

There are a few ways to do this today, but they're all OS-specific. One way would be to use a crate like https://docs.rs/rstack or https://docs.rs/stack-self, and install a custom panic handler that coordinates with rstack. But this uses ptrace and only works on Linux. It would also be a significant engineering project with careful consideration of edge cases.

Going to close this issue out, but if you decide to embark on this project I'd love to hear how it goes!
