### ISSUE TITLE
Doc: broken link

### ISSUE THREAD

**Issue by eugenesvk** [nextest-rs/nextest#1965]
https://nexte.st/docs/installation/macos/ refers to the link

> [See this comment on Hacker News for more.](https://news.ycombinator.com/item?%20id=24394150)

which doesn't exist

**Comment by sunshowers** [comment]
Thank you! Fixed in https://github.com/nextest-rs/nextest/commit/d5c13b30a0379b3112a65ada84c351ab2bc6859e.
