### ISSUE TITLE
feature suggestion: terminate slow tests after a given deadline and regard them as failed

### ISSUE THREAD

**Issue by steveeJ** [nextest-rs/nextest#213]
without this, terminating a frozen test suite relies on an external watcher that keeps track of time. since the test harness and nextest itself already track time for each test, it would be great to have deadline support natively in the cargo stack.

for this potential feature it's actually an advantage that nextest runs each test in a separate process, because terminating processes works reliably as opposed to terminating threads which requires cooperation.

**Comment by sunshowers** [comment]
Thanks for the request! Yes, I agree this makes a lot of sense.

It would be interesting to see how this interacts with #27. I guess we can apply it to the entire process.

**Comment by sunshowers** [comment]
This was released as cargo-nextest 0.9.18.
