### ISSUE TITLE
List of failed tests

### ISSUE THREAD

**Issue by AlphaCodingPilot** [nextest-rs/nextest#255]
when some of you're tests fail I would like to see a list of all the failed tests like in cargo test. This would help to see witch tests failed without having to scroll up the terminal (when you have many tests)

**Comment by sunshowers** [comment]
Thanks for the feature request! For now you can use `--failure-output immediate-final` to get full stdout/stderr, and once #256 lands and the next version of cargo-nextest is released (in the next few days) you'll be able to use `--final-status-level fail` to do the same. (To enable this globally for yourself, add the env var `NEXTEST_FINAL_STATUS_LEVEL=fail` to your environment.)

**Comment by AlphaCodingPilot** [comment]
these flags dont seem to work for me. I had something like this in mind:
```
failures:
    tests::foo
    tests::bar
```
