### ISSUE TITLE
Final status level (both from --final-status-level=XXX and NEXTEST_FINAL_STATUS_LEVEL=XXX) isn't respected

### ISSUE THREAD

**Issue by aolbrech** [nextest-rs/nextest#270]
Love this crate, thanks for all the hard work on this!

Using nextest version 0.9.18 and interested in the newly added feature --final-status-level=XXX to get feedback on which tests are slow or skipped. Tried running with `--final-status-level=slow` and nothing gets printed out, even if the regular print-out shows 5 slow tests. 

Slightly related, but would it be possible to have a different ordering for this final-status-level than the regular status-level? It would be very useful to see all failed, slow and skipped test printed out at the end of the summary. But in order to get the skipped tests, I will also get the passed ones which clutters this nice summary when there are thousands of tests.

**Comment by sunshowers** [comment]
Thanks for the report! Ah yeah, we don't track slow tests in that way.

I think it makes sense to do a reorder of levels for the final status (and also include both slow and flaky tests). Thanks again for the report.
