### ISSUE TITLE
Add help text explaining that --skip and --exact are covered by filter expressions

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#29]

**Comment by KaranLMungra** [comment]
hey @sunshowers can you describe the **--skip** and **--exact** args in more details.

**Comment by sunshowers** [comment]
Hi @KaranLMungra -- the options basically should mirror what `cargo test -- --skip` and `--exact` does, and I'd use those as a reference. However, I'd hold off on doing these as they're probably covered by #117 (and the impl should probably just use expressions).

**Comment by sunshowers** [comment]
I think this use case is sufficiently covered by #117:
* `--skip foo` is `-E '!test(foo)'`
* `--exact foo` is `-E 'test(=foo)'`

These flags also become really hard to reconcile with filter expressions in general.

I'll leave this open until filter expressions are no longer experimental. We may also want to add help text explaining that `--skip` and `--exact` are covered by filter expressions instead.
