### ISSUE TITLE
Test output strips ANSI colors

### ISSUE THREAD

**Issue by aaronabramov** [nextest-rs/nextest#302]
This is a great test runner! it cut the run time of our tests suite by about 10x, however i can't figure out how to configure colors in test output.

If i have a simple test that looks like:
```rust
#[test]
fn panic_with_ansi_colors() {
    panic!(
        "
        This is a panic!

        \u{1b}[1;31mThis line should be red\u{1b}[0m
        \u{1b}[2mThis line should be dimmed\u{1b}[0m

        "
    );
}
```

The colors in the terminal always get stripped from the output:

![Screen Shot 2022-06-21 at 2 53 24 PM](https://user-images.githubusercontent.com/940133/174886652-df09ff67-7b31-4aae-bb63-c34e92a998e0.png)

there's a `--color` option in the runner, but i assume it's for the runner itself and not the tests

**Comment by aaronabramov** [comment]
ah.. interesting. this seems to be intentional https://github.com/nextest-rs/nextest/blob/main/nextest-runner/src/reporter.rs#L992

is there any way to overwrite this?

**Comment by sunshowers** [comment]
Hi Aaron! Dug into the history and it looks like it was carried over from the initial implementation a long time ago. I think we can relax this as long as we output an ANSI reset at the very end.

**Comment by aaronabramov** [comment]
This is so so so much better. thank you!

![Screen Shot 2022-06-21 at 4 41 53 PM](https://user-images.githubusercontent.com/940133/174902101-f062f092-29df-4334-aaf1-facff8da7970.png)
