### ISSUE TITLE
Add homebrew/binstall/quickinstall support

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#31]
Currently, the only way to install cargo-nextest is with [the pre-built binaries](https://nexte.st/book/pre-built-binaries.html), or by using `cargo install`. It would be nice to add other binary installation mechanisms as well.

To consider:
* [x] ~Release signing~ (now tracked at https://github.com/nextest-rs/nextest/issues/369)
* [x] Integrate into [cargo binstall](https://crates.io/crates/cargo-binstall)
* [x] ~Point people to [cargo quickinstall](https://crates.io/crates/cargo-quickinstall)~ (we already do our own binary releases now)
* [x] Homebrew?

**Comment by sunshowers** [comment]
Initial version is at https://nexte.st/book/pre-built-binaries.html -- super easy to install from that URL.

**Comment by cwfitzgerald** [comment]
Thanks for this! For the windows side, modem windows 10 ships both real curl and real tar. The only difference is you need to type curl.exe to avoid the poweshell alias "curl".

**Comment by sunshowers** [comment]
@cwfitzgerald Got it, thanks! Any idea how to do the `${CARGO_HOME:-~/.cargo/bin}` substitution?

**Comment by cwfitzgerald** [comment]
Not a clue! :smile:

**Comment by CAD97** [comment]
For windows, it would be possible to provide packages for [scoop](https://scoop.sh/) and or [chocolatey](https://chocolatey.org/). [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) is provided by default in Windows 11 and available for Windows 10, but [doesn't yet support standalone installation](https://github.com/microsoft/winget-cli/issues/182).

**Comment by sunshowers** [comment]
Thanks @CAD97. Do you have experience with these? I don't really use Windows much these days so I'd really appreciate help creating whatever manifests etc need to be created.

**Comment by CAD97** [comment]
I've not made packages for any of these, so I don't have any advice to give beyond pointing at the official docs:

- [Scoop creating an app manifest](https://scoop-docs.vercel.app/docs/concepts/Creating-an-app-manifest.html)
  - [Format of an app manifest](https://scoop-docs.vercel.app/docs/concepts/App-Manifests.html)
  - [ripgrep's app manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/ripgrep.json)
- [Creating a chocolatey package](https://docs.chocolatey.org/en-us/create/create-packages)
  - [ripgrep's package](https://github.com/dstcruz/chocolatey-mypackages/tree/master/packages/ripgrep)
- [Contribute to the winget package repository](https://docs.microsoft.com/en-us/learn/modules/explore-windows-package-manager-tool/6-contribute-to-repository)

**Comment by remoun** [comment]
I'd love to see `cargo-binstall` support; [its README](https://crates.io/crates/cargo-binstall#supporting-binary-installation) says customizing where it looks for artifacts is as simple as adding `[package.metadata.binstall]` to `Cargo.toml`

**Comment by rouge8** [comment]
Added to Homebrew: https://github.com/nextest-rs/nextest/pull/361

**Comment by sunshowers** [comment]
We now have binstall and homebrew support, and https://github.com/nextest-rs/nextest/issues/369 tracks release signing. Closing as completed/with followups.
