### ISSUE TITLE
populate `<failure>` tags in JUnit output

### ISSUE THREAD

**Issue by hawkw** [nextest-rs/nextest#311]
The Jenkins JUnit XML format includes a `<failure>` tag for tests that error:
```xml

      <!-- failure indicates that the test failed.
           A failure is a condition which the code has explicitly failed by using the mechanisms for that purpose.
           For example via an assertEquals.
           Contains as a text node relevant data for the failure, e.g., a stack trace. optional -->
      <failure message="" <!-- The message specified in the assert. -->
	       type=""    <!-- The type of the assert. -->
	       >failure description</failure>
```

Many tools that ingest JUnit XML expect this tag to be populated a  `message` attribute and a text node failure description, but nextest does not currently populate these fields. It would be nice to add this.

I think we can do a reasonable heuristic implementation by simply scanning the test's stderr for the string "panicked at", and grabbing that line and anything following it as the "failure description". Of course, this wouldn't necessarily work if a non-default panic hook is in use, or changes to the default panic hook's output. But, we currently don't populate this tag _at all_, so I think it would be preferable to make a best-effort attempt in the cases where we can obviously extract a backtrace.

**Comment by sunshowers** [comment]
(note this is specifically about the message attribute of the failure tag)

**Comment by hawkw** [comment]
> (note this is specifically about the message attribute of the failure tag, or possibly the text contents of the tag)

Yeah, I've updated the issue to make that a bit clearer!

**Comment by sunshowers** [comment]
This is now out as cargo-nextest 0.9.23 (binaries will be available in 15-20 minutes).
