### ISSUE TITLE
Use environement variables from .cargo/config.toml

### ISSUE THREAD

**Issue by elBoberido** [nextest-rs/nextest#319]
For my project I need to run all the test sequentially. With `cargo test` I can add the `RUST_TEST_THREADS = "1" ` environment variable to `.cargo/config.toml`. I tried to add `NEXTEST_TEST_THREADS = "1"` to `.cargo/config.toml` but it seems `cargo nextest run` does not use it. I also couldn't reduce the number of thread with `.config/nextest.toml`.

Is there a way to do this via a configuration file? It would be ideal if environment variables defined in `.cargo/config.toml` could be used by `cargo nextest run`.

Being able to use a configuration file to specify this option would be the cherry on top of the nextest cake :)

**Comment by sunshowers** [comment]
Thanks for the report! I think we should just support this in the config. Main challenge is handling the non-sequential case—what about specifying things like num-cpus/2 or max(num-cpus, 16)?

Maybe we should just ignore that problem for now though.

**Comment by sunshowers** [comment]
Yeah we should just support either 1 or the special string "num-cpus" or similar.

**Comment by elBoberido** [comment]
@sunshowers well, `num-cpus = 1` wouldn't strictly mean that the tests run sequentially since one can have multiprocessing on 1 CPU or is `num-cpus = 1` internally identical to the `-j 1` option. Being able to specify that in the config file would also be sufficient.

**Comment by sunshowers** [comment]
Yeah, to be clear I'd like to support:

`test-threads = 1` (or 2, 3, etc)

or

`test-threads = "num-cpus"`

**Comment by sunshowers** [comment]
I'll get a new release out later this week with a test-threads config option.

I don't think we're ever going to support `.cargo/config`'s `env` option to control nextest itself -- however we may need to support it for the tests nextest runs.

**Comment by sunshowers** [comment]
This is now out as version 0.9.24.

**Comment by elBoberido** [comment]
@sunshowers thanks. Works like a charm
