### ISSUE TITLE
Set .cargo/config.toml [env] vars for tests at runtime

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#325]
Followup from #319. Looks like `cargo test` sets these env vars at runtime so nextest should as well.

**Comment by arxanas** [comment]
@sunshowers I'm interested in implementing this. Where should I add an `env` field and where should I populate it? I found some `config.toml`-parsing code for target triples, but I don't know if the environment variables should be kept in the same place.

**Comment by sunshowers** [comment]
Hi @arxanas -- thanks for expressing your interest!

The `[env]` field is part of `.cargo/config.toml` -- nextest already parses these files to emulate Cargo somewhat, so it's a matter of expanding that parsing.

See https://github.com/nextest-rs/nextest/issues/494#issuecomment-1225856439 for some more details, and https://doc.rust-lang.org/cargo/reference/config.html#env for the documented spec.

**Comment by arxanas** [comment]
@sunshowers thanks for the links. I was already able to parse the config variables, but I'm not sure where to store them during program execution. Are they a property of the test binary, or the test suite, or individual tests? If it should be part of the test suite or related structures, does that mean it should also be serializable, or should the env be picked up somewhere else (the test runner?)?

**Comment by sunshowers** [comment]
Like the other cargo configs, the env should be set for every test in a test run, so it's a property of the entire run.

I don't think there's any need to serialize it -- if you're referring to [build reuse support](https://nexte.st/book/reusing-builds.html), we expect the source code to be available on the target machine, and rely on that for other data contained in `.cargo/config.toml` already (such as information about the [target runner](https://nexte.st/book/target-runners.html)).

**Comment by arxanas** [comment]
@sunshowers I tried in https://github.com/nextest-rs/nextest/pull/534; let me know what you think of the approach.

**Comment by sunshowers** [comment]
I've left a few comments there, thanks!
