### ISSUE TITLE
Collaborate with libtest-mimic?

### ISSUE THREAD

**Issue by epage** [nextest-rs/nextest#38]
In reading the [expectations for custom test harnesses](https://nexte.st/book/custom-test-harnesses.html), it made me wonder if there was room for some kind of collaboration with libtest-mimic which provides a libtest-like interface for custom test harnesses.

Ideas
- Create a conformance CLI test crate and update libtest-mimic to use it
- Suggest libtest-mimic in the docs

**Comment by sunshowers** [comment]
Oh that would be fantastic! I didn't know libtest-mimic existed.

**Comment by sunshowers** [comment]
It looks like LukasKalbertodt/libtest-mimic#11 is the only blocker.

**Comment by sunshowers** [comment]
Once https://github.com/LukasKalbertodt/libtest-mimic/pull/11 is out, we can recommend libtest-mimic in the docs.
