### ISSUE TITLE
Ensure graceful experience for trybuild users

### ISSUE THREAD

**Issue by epage** [nextest-rs/nextest#39]
Unlike #38, there are "custom test harnesses" that are just libtest tests.  A very common one among proc-macro authors is `trybuild` (I also maintain `trycmd` which is modeled off of `trybuild`).

I have not tested this yet but I'm assuming there are issues because I *think* trybuild assumes it is the only test running and the output becomes difficult to read when other tests are running (from my `trycmd` experience)

**Comment by epage** [comment]
I wonder how willing dtolnay would be in using libtest-mimic.  It'll probably be a back-and-forth collaboration since I doubt libtest-mimic is ready as-is to support everything trybuild needs.

As for trycmd, I just copied trybuild in nearly every way even though I was used to libtest-mimic.

**Comment by sunshowers** [comment]
I think this should Just Work because nextest captures the output of each test separately. The only exception is with `--no-capture`, in which case nextest will run tests serially (so this should also Just Work).

**Comment by epage** [comment]
I'd recommend giving it a try in practice.  `trybuild`s output is not captured by `libtest` and it gives output as-if it was a custom test harness and capturing that output would be undesirable.

**Comment by sunshowers** [comment]
Currently nextest just captures trybuild output. I had a chat with David and it's unlikely that trybuild will do anything beyond that.
