### ISSUE TITLE
Pre-built binary release for musl?

### ISSUE THREAD

**Issue by messense** [nextest-rs/nextest#391]
Currently there is only x86_64-unknown-gnu binary release, it'd be nice to include a musl version.

I'd like to use it to test on Alpine Linux, see https://github.com/PyO3/maturin/pull/1004.

**Comment by sunshowers** [comment]
Hi, this would absolutely be welcome if you'd like to contribute a patch. Feel free to fork and use https://github.com/sunshowers/test-binary-release as a playground.

**Comment by sunshowers** [comment]
Released this as part of cargo-nextest 0.9.29 -- binaries will be available in the next 20 minutes.
