### ISSUE TITLE
Pre-built binary for ARM

### ISSUE THREAD

**Issue by teymour-aldridge** [nextest-rs/nextest#392]
Would it be possible build binaries for ARM (Linux)? I would be happy to submit a patch if this would be welcome.

**Comment by sunshowers** [comment]
Hi! ARM binaries would absolutely be welcome. You can use https://github.com/sunshowers/test-binary-release as a playground if you need to.

**Comment by sunshowers** [comment]
Released this as part of cargo-nextest 0.9.29 -- binaries will be available in the next 20 minutes.
