### ISSUE TITLE
Test runner config isn't picked up from --config

### ISSUE THREAD

**Issue by saethlin** [nextest-rs/nextest#400]
cargo-miri very very recently started passing the test runner as a command line argument instead of an environment variable. It looks to me like nextest doesn't handle that.

I took a shot at adding CLI parsing here, but I can't come up with a clean way to do it (I suspect I just don't know this codebase). It seems like the easiest place is to add some logic here: https://github.com/nextest-rs/nextest/blob/a809da0ddefe71297e804558199d23bfed637d9d/nextest-runner/src/cargo_config.rs#L251-L270
but the code there assumes that configs have a path they came from, and of course `--config` is not a path. But I can confirm that if I `push` something to that `Vec` and make up a path, cargo-miri works again.

**Comment by sunshowers** [comment]
Ah yeah, I believe we don't parse config arguments because they're currently unstable. I guess we should try and parse them a bit.

**Comment by sunshowers** [comment]
This is addressed in cargo-nextest 0.9.29 -- binaries should be out within the next 20 minutes.
