### ISSUE TITLE
Detecting invocations of nextest

### ISSUE THREAD

**Issue by mitsuhiko** [nextest-rs/nextest#416]
This probably relates to #27 somehow. For [insta](https://github.com/mitsuhiko/insta) I need a way to identify when a new run is started to discard data from old runs. The way I am doing this currently is via a global variable holding something rather unique:

https://github.com/mitsuhiko/insta/blob/66b57ddb3e55309ca621b46aab5a707f82c2f09c/src/snapshot.rs#L11-L14

This means that next time insta runs, it can discard older snapshot leftovers as it knows there are newer ones around. Unfortunately this breaks with nextest because of the process isolation (https://github.com/mitsuhiko/insta/issues/242)

One rather trivial way to fix/work around this issue were if nextest exports a `NEXTEST_RUN_ID` environment variable for all tests it runs pointed to a UUID. That way it would be trivial to detect different test invocations from each other.

Now I understand that this is quite unique to insta and if it's not useful I am also going to investigate alternatives, but that was the most trivial one I came up with so far.

**Comment by sunshowers** [comment]
Do you mean export an environment variable with a UUID for each separate test invocation? That honestly seems quite a reasonable thing to do.

There are several levels of uniqueness:
1. "test run UUID" (once per test)
2. "test instance UUID" (once per test instance)
3. "test attempt UUID" (for retries, once per attempt)

Which one will insta benefit from? My guess is 3.

**Comment by mitsuhiko** [comment]
In my case I need one UUID per `cargo nextest run`. For the individual tests the process / test has enough info to do this itself. For the attempts it would be nice to have a counter being injected though.

**Comment by sunshowers** [comment]
Got it. (There's currently an undocumented counter `__NEXTEST_ATTEMPT` which I guess we can replace with a documented one.)

Will try and get a new version of nextest out with this in the next 2-3 days -- you're also welcome to submit a patch, and I'd be happy to get this out sooner.

**Comment by mitsuhiko** [comment]
I pushed up a PR. This does not touch `__NEXTEST_ATTEMPT` just adds `NEXTEST_RUN_ID`. I felt puling in `uuid` with the `v4` feature is probably the cleanest way to implement this.

**Comment by sunshowers** [comment]
This is published as part of cargo-nextest 0.9.31. Thanks again for your contribution!
