### ISSUE TITLE
`cargo nextest run --no-run`?

### ISSUE THREAD

**Issue by olix0r** [nextest-rs/nextest#422]
In CI, we generally want to build tests separately from running them. As explained in [`matklad`'s excellent blog post](https://matklad.github.io/2021/09/04/fast-rust-builds.html):

> It is vital to know which part of your CI is the build, and which are the tests.

That is, we want to see build test failures independently from test execution failures, and we want to track the _build times_ separately from the test execution times.

To accomplish this, we typically run `cargo test --no-run` in one step, and then run `cargo test` in the following step. As we transition to nextest, I'm looking for similar functionality. I'm aware of `nextest archive`, but that feels heavyweight for our needs, and diverges substantially from the `cargo test` UX.

Are you amenable to supporting `cargo nextest run --no-run` flag? This would help us adopt nextest as a mostly-drop-in replacement for cargo test. Are there other ways to accomplish this?

**Comment by sunshowers** [comment]
Thanks for the question!

`cargo nextest list` will achieve this. To avoid printing out any test names, use `-E 'none()'`.

**Comment by olix0r** [comment]
@sunshowers Thanks! This should work for us.

**Comment by sunshowers** [comment]
The next version of nextest will have a `--no-run` anyway because it's quite a bit more intuitive, even though it does the exact same thing as `cargo nextest list -E 'none()'`.
