### ISSUE TITLE
Workspace support

### ISSUE THREAD

**Issue by augustocdias** [nextest-rs/nextest#43]
How can I execute tests in the child projects within a workspace?

I have some projects that define a workspace like this:

```
ROOT
|_ Cargo.toml # workspace config and main bin config
|_ src
|___ main.rs # main file
|___ tests
|______ test.rs # test file
|_ crate1
|___ Cargo.toml # lib config
|___ src
|_____ lib.rs # lib file
|_____ tests
|_______ test.rs # test file
|_ crate2
|___ Cargo.toml # lib config
|___ src
|_____ lib.rs # lib file
|_____ tests
|_______ test.rs # test file
```

So I have tests in the root of the workspace and in each child crate. How can I consolidate the junit reports from the tests? The way I run them in CI is basically running `cargo test` in each folder, including the root.

Do I need to add a config for each crate?

**Comment by sunshowers** [comment]
Thanks for the question! If you add just a single config at the workspace root within `.config/nextest.toml`, and run all of the tests in one go with `cargo nextest run --workspace`, it'll produce a single JUnit file with all the tests already combined. Of course if you have to run all the tests for each crate separately, you can use a post-processing tool to combine the JUnit files together.

**Comment by augustocdias** [comment]
No I don't need to run them separately. It was because of a limitation from the tooling. I'll try that. Tks
