### ISSUE TITLE
No detailed error message when `cargo test --no-run --message-format json-render-diagnostics` failed

### ISSUE THREAD

**Issue by messense** [nextest-rs/nextest#441]
```
Updating crates.io index
 Downloading crates ...
error: command `/usr/bin/cargo test --no-run --message-format json-render-diagnostics --features password-storage` exited
Error: Process completed with exit code 101.
```

See https://github.com/PyO3/maturin/runs/7644877524?check_suite_focus=true

Exit code 101 indicates that [the `cargo test` process panicked](https://rust-cli.github.io/book/in-depth/exit-code.html), but there isn't any detailed error message so it hard to know what's wrong.

**Comment by sunshowers** [comment]
Thanks for the report! That's really weird, nextest just passes the output through without doing anything. I think it's Cargo that's not producing the output.

What happens if you run the listed command by itself?

**Comment by messense** [comment]
```
    Updating crates.io index
 Downloading crates ...
Segmentation fault (core dumped)
```

Right, looks like a cargo issue on Alpine Linux, sorry for the noise.
