### ISSUE TITLE
unable to parse benchmark

### ISSUE THREAD

**Issue by BusyJay** [nextest-rs/nextest#46]
Any functions marked as benchmark by `#[bench]` using rust builtin bench will fail to be parsed.

```
   0: error building test list
   1: line 'byte::benches::bench_memcmp_decode_first_asc_large: benchmark' did not end with the string ': test'
```

If they are not supported on purpose, then ignore them may be a better alternative.

**Comment by sunshowers** [comment]
Yeah, I agree that lines ending with ": benchmark" should be ignored. I'll try to do a fix for this today.
