### ISSUE TITLE
Support negative --test-threads/--jobs parameter

### ISSUE THREAD

**Issue by sunshowers** [nextest-rs/nextest#495]
Port over https://github.com/rust-lang/cargo/pull/10844.

This is a great first issue and should take no more than a few hours to complete :) Here's the recommended series of steps:

1. Update the `TestThreads` parser and deserializer to handle negative integers: https://github.com/nextest-rs/nextest/blob/58999b1e350eb4865f6dcb1e8d3354820483f32c/nextest-runner/src/config.rs#L526-L534
   Use the logic at https://github.com/rust-lang/cargo/pull/10844/files#diff-f0c6e0ba24dc1403233aec133c8788a36c21b097514ea69994ff35253a07802a.
2. Add unit tests for this.

**Comment by OLUWAMUYIWA** [comment]
Interested in this. I will do the porting

**Comment by sunshowers** [comment]
@OLUWAMUYIWA awesome, thanks! Please comment here if you run into issues.

**Comment by OLUWAMUYIWA** [comment]
Will do. Thanks @sunshowers
