### ISSUE TITLE
--config arguments appears to be ignored by cargo nextest

### ISSUE THREAD

**Issue by mystenmark** [nextest-rs/nextest#498]
It appears that nextest ignores config flags specified as per https://doc.rust-lang.org/cargo/reference/config.html#command-line-overrides

Example: If I run

            cargo --config 'build.rustflags = [...]' test

it works as expected, and sets rustflags to the specified flags while building the test targets. However, changing `test` to `nextest run` causes the `--config` arg to be ignored.

I saw several other config-related issues have been opened, but this one seems to be distinct from those. If not, I apologize!

**Comment by sunshowers** [comment]
Thanks for the report! I believe if you pass in `--config` before `nextest run` it'll get eaten up by Cargo (this is honestly a bug in upstream Cargo I think, `--config` doesn't get passed down to plugins).

Instead, use this command:

```
        cargo nextest run --config 'build.rustflags = [...]'
```

which should work.

**Comment by mystenmark** [comment]
Oh hey that worked perfectly! Thanks so much!

**Comment by sunshowers** [comment]
@mystenmark I've reported this as https://github.com/rust-lang/cargo/issues/11031.
