### ISSUE TITLE
Support more `cfg()` in `Cargo.toml`

### ISSUE THREAD

**Issue by kdy1** [nextest-rs/nextest#499]
https://github.com/swc-project/swc/runs/8088642008?check_suite_focus=true

I tried using nextest for swc (https://swc.rs) but it failed with an error

```
  Downloaded aho-corasick v0.7.18
  Downloaded ahash v0.7.6
  Downloaded stdweb v0.4.20
  Downloaded subtle v2.4.1
  Downloaded stdweb-internal-runtime v0.1.5
  Downloaded terminal_size v0.1.17
  Downloaded url v2.2.2
  Downloaded unicode-normalization v0.1.19
error: error parsing Cargo metadata

Caused by:
  failed to construct package graph: for package 'browserslist-rs 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)': for dependency 'chrono', parsing target 'cfg(not(target = "wasm32-unknown-unknown"))' failed: cfg() expression has unknown predicate: target
Error: Process completed with exit code 96.
```

**Comment by sunshowers** [comment]
Thanks for the report! I've never seen the `target` predicate before, and it's not documented at https://doc.rust-lang.org/reference/conditional-compilation.html. Does it actually work?

**Comment by kdy1** [comment]
Yeap, `cargo test` works without any problem

**Comment by sunshowers** [comment]
I checked and `target` is definitely not supported by Cargo -- it always evaluates to false. Guess we should do the same instead, but as it currently exists, the conditionals in https://github.com/browserslist/browserslist-rs/blob/main/Cargo.toml#L54-L61 do not work. The first one always evaluates to false and the second one always evaluates to true.

**Comment by kdy1** [comment]
Oh.. I didn't know it, thanks! I'll file an issue on browserslist-rs instead

**Comment by kdy1** [comment]
Opened https://github.com/nextest-rs/nextest/issues/499 , but seems like cargo support target-specific dependencies

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies

**Comment by sunshowers** [comment]
Ah yeah, looks like browserlist has fixed its issue!

The next version of nextest will silently evaluate incorrect predicates to false, though I'm tempted to add a warning.
