### ISSUE TITLE
[question] How can I redirect all outputs to a file (bash shell) ? 

### ISSUE THREAD

**Issue by jiangying000** [nextest-rs/nextest#514]
When running `cargo nextest run -v --lib  > build/nextext-out-v-lib` , output are going directly to console, and file **build/nextext-out-v-lib** is always empty.

**Comment by jiangying000** [comment]
get one solution: `cargo nextest run -v --lib  > build/nextext-out-v-lib 2>&1`

**Comment by sunshowers** [comment]
Yes, as you figured out, nextest's output goes to standard error not standard output. That's why the `2>&1` is required.
