### ISSUE TITLE
[question] Is there any way I can print timestamp with every line of log ?

### ISSUE THREAD

**Issue by jiangying000** [nextest-rs/nextest#515]
for example when running `cargo nextest run --timestamp`

the log might be look like, i.e. add a timestamp before every line of log

    Mon, 05 Sep 2022 19:49:23 GMT Compiling nextest-workspace-hack v0.1.0 (/home/runner/work/nextest/nextest/workspace-hack)
    Mon, 05 Sep 2022 19:49:23 GMT Compiling nextest-filtering v0.2.1 (/home/runner/work/nextest/nextest/nextest-filtering)
        Finished dev [unoptimized + debuginfo] target(s) in 59.24s
    Mon, 05 Sep 2022 19:50:27 GMT PASS [   0.025s]               cargo-nextest dispatch::tests::test_test_binary_argument_parsing
    Mon, 05 Sep 2022 19:50:27 GMT PASS [   0.241s]               cargo-nextest dispatch::tests::test_argument_parsing

**Comment by sunshowers** [comment]
Thanks for the question! nextest doesn't have a builtin way to do this, but you can use Unix tools like awk. For example:

https://stackoverflow.com/questions/65787358/adding-timestamp-to-output-with-awk
