### ISSUE TITLE
New module path coloring does not work

### ISSUE THREAD

**Issue by tranzystorek-io** [nextest-rs/nextest#52]
After updating to 0.9.4, my paths remain in the default text color:
![image](https://user-images.githubusercontent.com/5671049/154432163-8e51d15c-8332-416d-b69f-ce07cad8d5dc.png)

Env:
Windows Terminal 1.12.10393.0
Zellij 0.24.0

**Comment by sunshowers** [comment]
As another example, it looks like your terminal's theme doesn't follow bold settings. The binary name (eg `untangle::cli_test`) and test name should appear in bold.

**Comment by tranzystorek-io** [comment]
I'm using https://draculatheme.com/, here's a run of https://www.npmjs.com/package/colortest:
![obraz](https://user-images.githubusercontent.com/5671049/154548395-3c693986-ca35-44f2-81d7-86ce38159d26.png)

Everything seems fine 🤔

**Comment by sunshowers** [comment]
Just tried it out on Windows, seems to work for me! Could you run cargo nextest --version and ensure that you're running 0.9.4?

![image](https://user-images.githubusercontent.com/180618/154576539-912891b8-d445-4e4b-b9c7-cb0a8308a440.png)

**Comment by foresterre** [comment]
To add another sample, it also seems to work for me:

![2022_02_18_WindowsTerminal_905_253_7UtcjTPFGg](https://user-images.githubusercontent.com/5955761/154601326-7603b6e6-3403-4060-8f5a-f532f4248976.png)


windows-terminal: 1.12.10393.0
Campbell color scheme (included with windows-terminal)

**Comment by tranzystorek-io** [comment]
> Could you run cargo nextest --version and ensure that you're running 0.9.4?

![obraz](https://user-images.githubusercontent.com/5671049/154632398-9b7e88f3-04bb-482b-ac5b-c9dae8f9378f.png)

This is really weird, I tried disabling `zellij`, switching the color scheme to Campbell, or even switching shell to bash but the problem persists.

It also doesn't change when I try running tests natively on WIndows instead of WSL.

**Comment by tranzystorek-io** [comment]
Update: I tried switching from Windows Terminal to alacritty but without success:

![obraz](https://user-images.githubusercontent.com/5671049/154692858-e286f290-2728-4d08-ab53-e371d3171cbe.png)

Maybe it's an issue on Windows 11...?

**Comment by yamafaktory** [comment]
Hello folks,

First of all, thanks a ton @sunshowers for this awesome tool ❤️!

I can confirm the issue which might not be platform / terminal related.

I'm on Manjaro XFCE (linux) and using either the default terminal - xfce4-terminal - or Alacritty with the latest `nextest` release - via cargo install - reproduces the issue. The weird thing is that using a fork of the latest `main` branch locally works perfectly fine in both terminal 🙈.

## Alacritty

![image](https://user-images.githubusercontent.com/465519/154842837-c6c8f57f-6038-41c3-b71b-db158cb1d854.png)

## xfce4-terminal

![image](https://user-images.githubusercontent.com/465519/154842879-49271778-b040-4a49-be41-53d36e5d90ca.png)

N.B.: I've noticed two opened issue on the `owo-colors` side (https://github.com/jam1garner/owo-colors/issues/45 & https://github.com/jam1garner/owo-colors/issues/41). However, based on the results I get, I'm not sure why it would behave like that 🤷.

**Comment by sunshowers** [comment]
Ahhha, thanks for diagnosing that! I think I forgot to release a new version of nextest-metadata, will do that + a new version of cargo-nextest shortly.

Note that you can install binaries via https://nexte.st/book/pre-built-binaries.

**Comment by yamafaktory** [comment]
@sunshowers awesome, thanks!

**Comment by tranzystorek-io** [comment]
Thank you very much @yamafaktory @sunshowers!
