### ISSUE TITLE
Final output is missing informations included in immediate output

### ISSUE THREAD

**Issue by poliorcetics** [nextest-rs/nextest#521]
I have `nextest` configured to run with `immediate-final` on failure.

In immediate output, I see the following:

```
     SIGSEGV [   0.014s]                         my-crate tests::my_test
--- STDOUT:                                      my-crate tests::my_test ---
running 1 test
```

In the final output I see:

```
--- STDOUT:                                      my-crate tests::my_test ---
running 1 test
```

The reason for failure `SIGSEGV` has been lost. On a small crate with few tests it's okay, but on one with pages and pages of them, it's easily lost and makes finding out why the test failed less convenient.

**Comment by sunshowers** [comment]
Thanks for the report! I agree that this is suboptimal. Will put up a fix shortly.

**Comment by poliorcetics** [comment]
Thanks a lot !
