### ISSUE TITLE
Compatibility with coverage tools?

### ISSUE THREAD

**Issue by pwoolcoc** [nextest-rs/nextest#56]
Is there any way to use this in conjunction with coverage tools? Maybe it would be better to go see if the coverage tool has support for this rather than the other way around, but if someone here has gotten nextest working with a coverage tool I'd love to hear about it.

**Comment by sunshowers** [comment]
I'm not aware of any current efforts, but I'd certainly welcome some discussion about it. My ideal solution would involve not baking the specifics of a particular coverage tool into nextest itself, and having some sort of inter-process protocol to communicate with a daemon as necessary instead.

**Comment by pwoolcoc** [comment]
turns out it works just fine with `rustc`'s built-in instrumentation and llvm's coverage tools. Repo is here: https://github.com/pwoolcoc/nextest-cov-example, output looks like:

<img width="1626" alt="image" src="https://user-images.githubusercontent.com/620392/154739713-c333eb67-1256-4ba7-a80f-6ee45cdd40c3.png">

**Comment by skyzh** [comment]
I'm working on integrating nextest with llvm-cov. https://github.com/taiki-e/cargo-llvm-cov/pull/144

If the above PR gets merged, generating coverage with nextest should be as simple as `cargo llvm-cov nextest`

**Comment by sunshowers** [comment]
@skyzh that's awesome! thank you

**Comment by sunshowers** [comment]
> maybe we can update docs and close this issue?

Thanks again for getting this upstream! llvm-cov is one of several coverage tools one might want to use, so let's try and write up some generic documentation for this as well before closing this issue.

**Comment by sunshowers** [comment]
https://github.com/nextest-rs/nextest/pull/119 has more documentation.

**Comment by sunshowers** [comment]
https://nexte.st/book/test-coverage.html has the documentation!
