### ISSUE TITLE
`list` (maybe `run`?) doesn't respect `CARGO_TARGET_{TRIPLE}_RUNNER`

### ISSUE THREAD

**Issue by Jake-Shadle** [nextest-rs/nextest#57]
We build and test Windows binaries from Linux, and use [`CARGO_TARGET_{TRIPLE}_RUNNER`](https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner) to specify (in our case) `wine` so that we can test the binaries, however nextest doesn't seem to read this configuration and attempts to directly execute the test binaries when performing the initial test list before running the tests.

I can add support for this tomorrow in a PR, just thought I would file this issue for visibility. Great work on this btw!

**Comment by sunshowers** [comment]
To determine platform etc support, you'll probably want to just use target-spec, which depends on your own cfg-expr library!

**Comment by sunshowers** [comment]
@Jake-Shadle I had a look at cargo's config and it feels like it'll be really hard to emulate all of it correctly. What do you think of adding this to nextest.toml instead?

**Comment by sunshowers** [comment]
@Jake-Shadle this is now released as 0.9.6 -- could you confirm that https://nexte.st/book/target-runners.html makes sense to you? Thanks!

**Comment by Jake-Shadle** [comment]
Thanks for the quick release! Yes, the docs make sense to me, I think the biggest thing is that people who are already using one of those methods for setting a target runner will be able to drop in nextest with no problems. :slightly_smiling_face:
