### ISSUE TITLE
Don't warn/immediately timeout when terminate-after=1?

### ISSUE THREAD

**Issue by saethlin** [nextest-rs/nextest#571]
I am using nextest non-interactively, so I don't really want to be warned that a test has been running for a while, I just want it to be killed. So I am using a config that looks like this:
```
[profile.default-miri]
slow-timeout = { period = "60s", terminate-after = 1 }
```
And I get output that looks like this:
```
        SLOW [> 60.000s]           regex::backtrack crazy::nest_limit_makes_it_parse
     TIMEOUT [  60.052s]           regex::backtrack crazy::nest_limit_makes_it_parse
```
I'm not sure it makes a whole lot of sense to print the slow notification first here. Could nextest just emit:
```
     TIMEOUT [  60.000s]           regex::backtrack crazy::nest_limit_makes_it_parse
```

**Comment by sunshowers** [comment]
So I actually thought about this! My big concern was that the `TIMEOUT` message is printed *after* the process terminates, which can take up to 10 seconds longer if the process somehow blocks SIGINT.

I think we should replace that last `SLOW` message with `TERMINATING` or something.

**Comment by saethlin** [comment]
I agree with what you're saying for the general case, but of course my follow-up question is...

Can I tell nextest that I don't care about graceful shutdown, so that I just see the `TIMEOUT` instead of the `TERMINATING`? I'm even interested in nextest using SIGKILL instead, so that it doesn't even have to consider a delay between timeout and the test actually shutting down. (of course I have no idea how this would/could work on other platforms)

**Comment by sunshowers** [comment]
Nextest's kill procedure is currently hardcoded:
* send SIGTERM
* wait 10 seconds for the process to die
* if it doesn't die within those 10 seconds, send SIGKILL

We could make this timeout configurable and set it to 0 for an immediate SIGKILL, I guess. Would you like to work on this?

(On Windows we always do a SIGKILL equivalent immediately)

**Comment by saethlin** [comment]
Yup, I'm going to look into this. I'll let you know if I get stuck.

**Comment by sunshowers** [comment]
This is going to be out as part of cargo-nextest 0.9.39, releasing shortly. Thanks for working on this!
