### ISSUE TITLE
Why used hashed partition?

### ISSUE THREAD

**Issue by memark** [nextest-rs/nextest#604]
Having read [the docs for both counted and hashed partition](https://nexte.st/book/partitioning.html?highlight=partition#partitioning-test-runs-in-ci), I fail to understand what the (if any) advantages of hashed partitioning would be?

>For sufficiently large numbers of tests, hashed sharding produces roughly the same number of tests per bucket. However, smaller test runs may result in an uneven distribution.

This suggests it's equally good as counted partition at high counts, and worse at low counts. Is there an obvious upside I'm missing?

**Comment by sunshowers** [comment]
Thanks for your question!

The main advantage of hashed partitioning is that it is robust to filtering. No matter what filtering you specify, a test will always be assigned to the same hash bucket.

Also I guess hashes are the canonical way to do sharding. It would be a bit weird for nextest to not provide it as an option imho!

**Comment by memark** [comment]
Thank you, good answer!
