### ISSUE TITLE
Run parallel tests under MPI

### ISSUE THREAD

**Issue by jedbrown** [nextest-rs/nextest#605]
In scientific computing, it's common to have tests that must run with multiple processes (that communicate with each other), often using MPI. In [rsmpi](https://github.com/rsmpi/rsmpi/), we have a bunch of separate executables and a clumsy [bash script](https://github.com/rsmpi/rsmpi/blob/main/ci/run-examples.sh) that uses [`cargo-mpirun`](https://github.com/AndrewGaspar/cargo-mpirun/blob/master/src/mpirun.rs) to execute those. This is slow and has poor usability. Some of us are working on more Rust libraries that use MPI, so this need will continue to grow and nextest support would be a huge enabler.

I'm curious whether you might consider contributions that introduce the concept of tests that should be executed in parallel. I could imagine something like `#[nextest::mpi(n=[2,3,5])]` saying to launch this test using 2, 3, and 5 processes (separate invocations to test that it behaves correctly with different amounts of parallelism). The normal way to do this is via a launcher program that spawns multiple processes with the same executable, but environment variables such that MPI library initialization will understand how to communicate efficiently between them.
```
mpiexec -n 2 target/.../the-binary --possible-arguments
```

If you would consider such contributions, do you have any suggestions for how to introduce this concept/where to implement?

**Comment by jedbrown** [comment]
Thanks! I'll give that a try. Does nextest have a concept of tests needing more than one "slot" of parallelism? I ask because parallel jobs exhibit severe slow-down when oversubscribed (more processes than logical cores). This could be handled instead by a resource manager in the test harness that gently blocks each job until enough slots are available to `mpiexec`. (Some environments have external resource managers, but they're too much hassle for each contributor to configure and generally increase single job latency.)

**Comment by sunshowers** [comment]
Ah sadly, no, that's not yet supported -- it's going to need a specific primitive that's a [tokio semaphore](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html) variant to work. The variant needs to behave somewhat differently from the one linked -- it must let you dip into the negatives, then block any waiters after that.

I've chatted with the Tokio folks about potentially building a primitive like that but it hasn't been implemented yet.

**Comment by sunshowers** [comment]
Good news: I've figured out how to do this using a variant of `buffer_unordered` instead. https://github.com/sunshowers/buffer-unordered-weighted/blob/main/src/lib.rs

Hoping to ship this in the next version of nextest.

**Comment by jedbrown** [comment]
Ooh, wonderful! I'll be an eager user.

**Comment by sunshowers** [comment]
cargo-nextest 0.9.42 is going to be out in a few minutes, and it has a [new `threads-required` option](https://nexte.st/book/threads-required). Hope this helps!

**Comment by jedbrown** [comment]
Thanks! I started out by writing a custom harness that builds and runs examples, but found it's nicer to use `cargo nextest run --example abc` (see #681) in part because things like features automatically match between the `cargo test`/`cargo nextest run` invocation and the way the binary is built, and also because I don't have to deal with parallel `cargo build` instances fighting for their locks.

```rust
#[cfg(test)]
mod tests {
    #[test]
    #[ignore]
    fn only_main() {
        super::main();
    }

    #[test]
    fn mpiexec_n2() {
        let me = std::env::args().next().unwrap();
        let mut cmd = std::process::Command::new("mpiexec");
        cmd.args(&[
            "-n",
            "2",
            &me,
            "tests::only_main",
            "--nocapture",
            "--exact",
            "--ignored",
        ]);
        let status = cmd.status().unwrap();
        assert!(status.success());
    }
}
```

The `mpiexec_n2` naming enables using filter expressions to set `threads-required`. This works great and produces clean output with `nextest`, but is kind of chaotic with `cargo test`.
```console
 cargo test --example demo
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests examples/demo.rs (target/debug/examples/demo-8c2033b124880e30)

running 2 tests
test tests::only_main ... ignored

running 1 test

running 1 test
Process 1 got message [4.0, 8.0, 15.0].
Status is: Status { source_rank: 0, tag: 0 }
test tests::only_main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.06s

test tests::only_main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.06s

test tests::mpiexec_n2 ... ok

test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 1.22s
```

Do you know of a way to execute the test executable (like `target/debug/examples/demo-8c2033b124880e30`) in a way that directly calls a function (classic `main()` in this case, or the ignored test I'm using here) without any other printing?

**Comment by sunshowers** [comment]
Hi @jedbrown, missed this earlier. Do you still need help? I'm not able to quite parse what you're looking for.

**Comment by jedbrown** [comment]
Thanks, and sorry for my late reply. I think I know what needs to be done. My question was murky because I didn't have a clear understanding of what was `#[test]` magic that could not be implemented using a custom test harness. I prototyped what I think is will be a working strategy for (close to) what I wanted, though I haven't had time to build it out yet. I guess this issue can be closed or I'll post here with a link when I find time to build what I had intended.

**Comment by sunshowers** [comment]
Gotcha. The main magic that the test macro lets you do it to collect all instantiations of the macro and be able to enumerate them. There's no stable way to do this that's built into the Rust language (you can in principle write to a file in a proc macro, but you're not supposed to do that).

https://github.com/dtolnay/linkme also lets you do this but only works on the three major platforms.

**Comment by sunshowers** [comment]
Closing this for now, feel free to open new issues as needed. Thanks.
