### ISSUE TITLE
Help filtering test

### ISSUE THREAD

**Issue by azzamsa** [nextest-rs/nextest#621]
Hi.

I am trying to set ` --test-threads 1` to `tests/user`. Previously, I use `cargo nextest run --all-targets --test-threads 1`. 
It works well but is very slow. Because other tests don't need  ` --test-threads 1` .

I try to use the `per-test overrides` feature but had no luck.

```diff
new file   .config/nextest.toml
@@ -0,0 +1,4 @@
+[[profile.default.overrides]]
+# filter = 'test(/^user::/)'
+filter = 'package(tin)'
+test-threads = 1
modified   justfile
@@ -56,7 +56,7 @@ _unit-test:
 
 # Test the codebase.
 test:
-    cargo nextest run --all-targets --test-threads 1
+    cargo nextest run --all-targets
 ```
 
 Using ` filter = 'test(/^user::/)'`,  `filter = 'test(/^test::user::/)'`, and `filter = 'package(tin)' give no luck.
 
 ```
 tin/tests on  master [+] via 🦀 v1.64.0
❯ tree
.
├── health
│  ├── mod.rs
│  └── tests.rs
├── meta
│  ├── mod.rs
│  └── tests.rs
├── user
│  ├── create_user.rs
│  ├── create_user_without_full_name.rs
│  ├── delete_user.rs
│  ├── duplicate_username.rs
<snip>...
```

Btw, do we have another *suitable* place for asking for help? Such Discussion tab.

Thanks a lot for the nextest! :heart:

**Comment by sunshowers** [comment]
Hi there, thanks for the feature request!

`test-threads` is not currently supported by per-test overrides; you can look at the set of supported tests [here](https://nexte.st/book/per-test-overrides.html). Maybe we should support "num-cpus" for `threads-required`, which should solve your problem I believe.

**Comment by azzamsa** [comment]
> `test-threads` is not currently supported by per-test overrides; you can look at the set of supported overrides [here](https://nexte.st/book/per-test-overrides.html). Maybe we should support "num-cpus" for `threads-required`, which should solve your problem I believe.

Oh, I see.

> Maybe we should also warn on unsupported config options.

Agree. It avoids such this confusion :)

Thanks for nextest!

**Comment by azzamsa** [comment]
> Maybe we should support "num-cpus" for threads-required, which should solve your problem I believe

@sunshowers Should I open a new ticket to track this as a feature request?
