### ISSUE TITLE
[Question] Support for no_std and custom test-framework?

### ISSUE THREAD

**Issue by TornaxO7** [nextest-rs/nextest#663]
Hello! I'd like to ask if this crate supports two features:
1. Can I use nextest in a `no_std` environment?
2. Can I implement my own test-framework with `nextest`?

## Context
I'm currently trying to implement a kernel in rust, so I'd need to tell cargo somehow to start `qemu` and running the executable in it. Sadly, the provided [`custom_test_framework`](https://doc.rust-lang.org/unstable-book/language-features/custom-test-frameworks.html) feature gives me a lot of problems and it's [eRFC is sadly closed](https://github.com/rust-lang/rust/issues/50297). So it's not easy (or with only a lot of work) to have a working testing environment without std.

**Comment by sunshowers** [comment]
Thanks for the questions?

> Can I use nextest in a no_std environment?

Nextest itself isn't no_std compatible, however you can run no_std tests for it using a [target runner](https://nexte.st/book/target-runners.html). I think based on what you've described, trying out a target runner might be the best approach.

> Can I implement my own test-framework with nextest?

I'm not entirely sure what this means. Nextest is open source and you're free to do whatever you like with it, of course. But nextest is a custom test runner, not a framework or harness.

**Comment by TornaxO7** [comment]
Ok, thank you for the information!
