### ISSUE TITLE
List and run command doesn't match on execution

### ISSUE THREAD

**Issue by Freyskeyd** [nextest-rs/nextest#699]
Hello,

I'm working with a project using multiple crates in a single workspace structure.
Some crates are top level crate that use other crate as dependencies.
I tried to make the `filter-expr` work to execute tests of a particular branch of crate but without success.
I scratch my head to understand how the `filters` were working and I'm sorry if this issue end up being useless if I miss something in the doc.

My issue is that the `cargo nextest list -E 'deps(my-deps)' --workspace` is giving me a list of tests that I want to see executed. The `list` command show (for me) the expected output.

Using the same filter on the `run` command do nothing, it doesn't execute any tests (flagged `0` tests across X `binaries`).

Thanks for reading !

**Comment by sunshowers** [comment]
This is now out as part of cargo-nextest 0.9.47. Thanks!
