### ISSUE TITLE
In .cargo/config `runner` can be an array of string

### ISSUE THREAD

**Issue by Guiguiprim** [nextest-rs/nextest#73]
Recently support for custom runner was added, but it fails to parse some valid config file.

We currently assume that the runner parameter is a simple string, but it can be an array of string.

 see [target.runner](https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner): `Type: string or array of strings ([program path and args])`

**Comment by sunshowers** [comment]
Whoops! Going to try and fix this now.

**Comment by Guiguiprim** [comment]
@sunshowers I just opened a PR for this !

**Comment by sunshowers** [comment]
Addressed in #75 and version 0.9.8. Thanks!
