### ISSUE TITLE
Run test parallely  when `--no-capture` flag is enabled

### ISSUE THREAD

**Issue by eval-exec** [nextest-rs/nextest#740]
I just noticed there is a Runner option: 
```
--no-capture              Run tests serially and do not capture output
```
Why tests run serially when `--no-capture` flag is enabled? 
I think it would be more convenient if nextest can run tests parallely when `--no-capture` is specified. And the `--nocapture` for `cargo test` is parallelism. 

Can I do some work to make nextest run parallely when `--no-capture` flags is enabled?

**Comment by sunshowers** [comment]
Hi there! It's because test output would overlap across tests which I've found confusing with cargo test in the past.

**Comment by eval-exec** [comment]
We can make tests run parallely, and print every test's output after its
finished.

Like: redirect every tests' stdout and stderr to a buffer, when one test
finished, then flush the output buffer to console. Do you think it's a good
idea? I would like to work on this.

Rain ***@***.***> 于 2022年12月29日周四 01:41写道：

**Comment by sunshowers** [comment]
That's a different option: `--success-output immediate`

**Comment by eval-exec** [comment]
> That's a different option: `--success-output immediate`
Thank you.

Are the default value of `--failure-output` and `--success-output` is `never`?

Is the effect of `cargo nextest run --all` is as same as `cargo nextest run --all --failure-output never --success-output never` ?

**Comment by sunshowers** [comment]
The default value for `--failure-output` is `immediate` and for `--success-output` is `never`. You can see them as part of the default config: https://nexte.st/book/configuration.html.

**Comment by eval-exec** [comment]
> 

Thank you. I think it would be more convenient if default value can be indicated in the help message of `cargo nextest run -h`:

```
Reporter options:
      --failure-output <WHEN>       Output stdout and stderr on failure [env: NEXTEST_FAILURE_OUTPUT=] [possible values: immediate, immediate-final, final, never]
      --success-output <WHEN>       Output stdout and stderr on success [env: NEXTEST_SUCCESS_OUTPUT=] [possible values: immediate, immediate-final, final, never]
      --status-level <LEVEL>        Test statuses to output [env: NEXTEST_STATUS_LEVEL=] [possible values: none, fail, retry, slow, leak, pass, skip, all]
      --final-status-level <LEVEL>  Test statuses to output at the end of the run [env: NEXTEST_FINAL_STATUS_LEVEL=] [possible values: none, fail, flaky, slow, skip, pass, all]
      --hide-progress-bar           Do not display the progress bar [env: NEXTEST_HIDE_PROGRESS_BAR=]


```

**Comment by sunshowers** [comment]
Ahh, unfortunately the default value comes from configuration and AFAIK there isn't an easy way to hook into clap's derive functionality to generate help text at runtime (unless you know of a way!)

**Comment by eval-exec** [comment]
Thanks
