### ISSUE TITLE
Odd warning about `insta` when installing

### ISSUE THREAD

**Issue by FrankReh** [nextest-rs/nextest#773]
When I run `cargo install --path .` from cargo-nextest, I get a warning but when I simply build the release, I don't. I see `insta` had something recently with version 1.25 and 1.26, but I don't  know why build would be clean and install would not be. (On Linux.)

```sh

 cargo-nextest $ cargo build --release
    Finished release [optimized] target(s) in 0.29s
 cargo-nextest $ cargo install --path .
  Installing cargo-nextest v0.9.49 (/home/ubuntu/clean/nextest/cargo-nextest)
    Updating crates.io index
warning: profile package spec `insta` in profile `dev` did not match any packages

	Did you mean `instant`?
    Finished release [optimized] target(s) in 0.36s
   Replacing /home/ubuntu/.cargo/bin/cargo-nextest
    Replaced package `cargo-nextest v0.9.49 (/home/ubuntu/clean/nextest/cargo-nextest)` with `cargo-nextest v0.9.49 (/home/ubuntu/clean/nextest/cargo-nextest)` (executable `cargo-nextest`)
```

**Comment by sunshowers** [comment]
Thanks -- this is due to https://github.com/nextest-rs/nextest/blob/a2da5ea4eb2d7da0de8dde0132a475e09339133c/Cargo.toml#L17-L22 which I guess `cargo install` has issues with, because these are dev-only dependencies. The warning can safely be ignored.
