### ISSUE TITLE
Confusing error when trying to use with miri without `run`

### ISSUE THREAD

**Issue by Imberflur** [nextest-rs/nextest#809]
Trying to use `nextest` with `miri` I ran:

```sh
cargo +nightly miri nextest
```

Which produces:
```
error: unexpected argument '--target-dir'
```

This led me to think there was some incompatibility between the versions when I was really just missing a `run` [at the end](https://nexte.st/book/miri.html#usage).

**Comment by sunshowers** [comment]
Ah yeah, I can see that being confusing!

One way to fix this would be to implement https://github.com/nextest-rs/nextest/issues/800.

**Comment by sunshowers** [comment]
Looks like this was addressed upstream in miri.

```
% cargo +nightly miri nextest
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
fatal error: `cargo miri nextest` expects a verb (e.g. `run`)
```
