### ISSUE TITLE
Make nextest work with grcov

### ISSUE THREAD

**Issue by woss** [nextest-rs/nextest#810]
I'm trying to setup the grcov with the nextest and but i am keep getting this error
![image](https://user-images.githubusercontent.com/80440/218497219-4af2ec9e-30c1-4308-85dd-71f4b79370e2.png)

the command is this then the grcov is triggered
`LLVM_PROFILE_FILE="grcov-nextest-%p-%m.profraw" NEXTEST_TEST_THREADS=1 cargo nextest run`

Any help is appreciated.

**Comment by sunshowers** [comment]
Thanks for the report! Nextest works with llvm-cov: https://nexte.st/book/test-coverage.html

I don't know if anyone's integrated nextest with grcov -- there might be some integration work required to make that work.

**Comment by woss** [comment]
@sunshowers indeed, not sure how i missed that :) thankssss
