### ISSUE TITLE
[CLI difference] `cargo test -j4` also sets the number of build jobs

### ISSUE THREAD

**Issue by jalil-salame** [nextest-rs/nextest#833]
# Problem

`cargo test` and `cargo nextest run` differ in their API:

Cargo test only has `-j/--jobs` to specify the parallelism.
Nextest uses `--build-jobs` and `--test-threads`.

While I do agree with the separation, `-j` setting just the value for `--test-threads` is surprising.

# Proposed solution

Add a third option: `-j/--jobs` which sets the value for both `--test-threads` and `--build-jobs`, specifying `--build-jobs/--test-threads` explicitely overrides the value from `-j/--jobs`.

**Comment by sunshowers** [comment]
Thanks for the report! Unfortunately `-j` is already taken for `--test-threads`, which limits our options.

* I think adding a `--jobs` that isn't the same as `-j` is going to be confusing given that constraint.
* Changing `-j` to mean `--jobs` would also be confusing. Many people use `-j1` in CI to run tests in a single-threaded fashion, knowing that that doesn't affect the number of build jobs.

I think we're just going to have to live with this incompatibility. I think your suggestion would have definitely been better overall, but it's too late to change to that.

**Comment by jalil-salame** [comment]
Maybe keep it in mind if there ever is a 2.0 release/backwards incompatible release?

**Comment by sunshowers** [comment]
Yeah, for sure.
