### ISSUE TITLE
`libtest-mimic` test failure not recognised

### ISSUE THREAD

**Issue by niluxv** [nextest-rs/nextest#836]
I'm using a custom test harness using `libtest-mimic` (version 0.6.0), but when one of those tests fails, `cargo nextest run` still reports it as passed.

**Comment by niluxv** [comment]
Hm, it seems to require using [`Trial::with_kind`](https://docs.rs/libtest-mimic/0.6.0/libtest_mimic/struct.Trial.html#method.with_kind).

Example:
```rust
use libtest_mimic::{Arguments, Failed, Trial};

fn main() -> anyhow::Result<()> {
    let args = Arguments::from_args();
    let tests = vec![
        Trial::test("example.txt", erroring_test).with_kind("parse")
    ];
    libtest_mimic::run(&args, tests).exit();
}

fn erroring_test() -> Result<(), Failed> {
    // either return error or panic!, cargo nextest will still show as `PASS`
    //panic!();
    Err("Error, this doesn't work".into())
}
```

**Comment by sunshowers** [comment]
Ah thanks for the extended report. This is a bug in libtest-mimic.

**Comment by sunshowers** [comment]
I've proposed https://github.com/LukasKalbertodt/libtest-mimic/pull/30 in libtest-mimic which will fix this. For now, please avoid using `with_kind`.

**Comment by niluxv** [comment]
Thank you for looking into this!

**Comment by sunshowers** [comment]
This should be fixed with a libtest-mimic update. Thanks for the report!
