### ISSUE TITLE
nextest-metadata is outdated (`--format`)

### ISSUE THREAD

**Issue by kdy1** [nextest-rs/nextest#846]
```rust
let tests = ListCommand::new()
            .exec()
            .context("failed to get the list of tests using nextest")?;
```

The code above fails because `ListCommand` specifies `--format`

https://github.com/nextest-rs/nextest/blob/651bcaed8378b4daa4a36ac5782f050cc55e10dc/nextest-metadata/src/test_list.rs#LL83

**Comment by sunshowers** [comment]
Thank you for filing this! That should be `--message-format`.

Would you like to submit a PR with a test? If not I can try getting to it some time this weekend.
