### ISSUE TITLE
Allow specifying a default filter for a profile

### ISSUE THREAD

**Issue by neoeinstein** [nextest-rs/nextest#847]
I have some integration tests that require a backing data store to be available. By default, I'd like only the "unit" tests to run, but I'd like this to be something that any other user can do by just specifying `cargo nextest run`, rather than `cargo nextest run -E 'not (kind(test) and binary(integration))'`. I think that adding a property into the profile configuration would be great. This would then also enable "named" filters in a way, through the use of the profiles feature.

**Comment by sunshowers** [comment]
Hi, thanks for the question! I agree that this would be good. The main challenge here is presenting this in the UI -- we need to make it clear that it's not nextest's fault that only a subset of tests is being run.

**Comment by sunshowers** [comment]
This is now supported via the `default-set` config: https://nexte.st/docs/running/#running-a-subset-of-tests-by-default
