### ISSUE TITLE
Incorrect arguments passed to benchmarks

### ISSUE THREAD

**Issue by Wodann** [nextest-rs/nextest#871]
When I run nextest with `--all-targets`, testing of benchmarks fails with the following error message:

```
Error: creating test list failed
Caused by:
  for `rethnet_evm::bench/state`, command `/home/runner/work/hardhat/hardhat/target/debug/deps/state-3c982b29c4c2de0f --list --format terse` exited with code 2
--- stdout:

--- stderr:
Gnuplot not found, using plotters backend
error: Found argument '--format' which wasn't expected, or isn't valid in this context
Error: Found argument '--format' which wasn't expected, or isn't valid in this context
	If you tried to supply `--format` as a value rather than a flag, use `-- --format`
```

It seems like the `--format` argument that's passed follows the wrong convention

**Comment by sunshowers** [comment]
Thanks for the report! This is actually a bug in criterion: #96.

The fix to make criterion support nextest has landed (https://github.com/bheisler/criterion.rs/pull/602), but has not been released yet.

Closing as a dup of #96.
