### ISSUE TITLE
Installing cargo-nextest through Homebrew leads to issues by adding a secondary Rust installation

### ISSUE THREAD

**Issue by pvditto** [nextest-rs/nextest#872]
The installation instructions for `cargo-nextest` [link](https://nexte.st/book/pre-built-binaries.html#homebrew) to a Homebrew formula, however, installing this formula leads to issues with Rust tooling by adding a brew-installed rust that shadows the one installed through e.g. rustup.

I have [reported this issue](https://github.com/Homebrew/homebrew-core/issues/124998) to the Homebrew project but they have reservations against fixing this issue because a Rust installation is required for running cargo-nextest. So, the brew formula is broken for anybody who already has Rust in order to make it work for people who don't have Rust on their system.

I recommend adding a disclaimer to the installation instructions that the Homebrew package should only be used if no other Rust installation exists in the system or lobbying Homebrew to fix the issue.

**Comment by sunshowers** [comment]
Oooof, yeah, that's really unfortunate. I'll add a note.

**Comment by rami3l** [comment]
@sunshowers The relevant change in 7869944 can now be safely reverted: https://github.com/Homebrew/homebrew-core/pull/134064.

**Comment by sunshowers** [comment]
@rami3l, thanks I missed that earlier. I fixed this in 7e0e313f634cb323045b5130d94bf3f33270d7ea.
