### ISSUE TITLE
false negative in tests of libtest2-mimic

### ISSUE THREAD

**Issue by zjp-CN** [nextest-rs/nextest#874]
Reproduce:

```
git clone https://github.com/epage/pytest-rs.git
cd pytest-rs/crates
cargo nextest run -j 8 --workspace
```

and you'll see tests in [all_passing](https://github.com/epage/pytest-rs/blob/main/crates/libtest2-mimic/tests/testsuite/all_passing.rs) failed

```
...
     Summary [   6.820s] 25/44 tests run: 17 passed, 8 failed, 0 skipped
        FAIL [   6.634s] libtest2-mimic::testsuite all_passing::filter_one
        FAIL [   6.594s] libtest2-mimic::testsuite all_passing::filter_two_and_skip
        FAIL [   4.474s] libtest2-mimic::testsuite all_passing::normal
        FAIL [   5.621s] libtest2-mimic::testsuite all_passing::skip_exact
        FAIL [   6.601s] libtest2-mimic::testsuite all_passing::skip_nothing
        FAIL [   5.125s] libtest2-mimic::testsuite all_passing::skip_two
        FAIL [   4.438s] libtest2-mimic::testsuite all_passing::terse_output
        FAIL [   3.353s] libtest2-mimic::testsuite main_thread::check_test_on_main_thread
```

Full output is [here](https://gist.github.com/zjp-CN/dca03422787f1818c12a1c682dd6c365).

But they all succeed if `cargo test --workspace` or `cargo nextest run -j 8 --workspace -- all_passing`

**Comment by sunshowers** [comment]
I think this is best directed towards the libtest2-mimic folks. Please file an issue there, thanks!

**Comment by sunshowers** [comment]
My guess from a quick look is that they need to isolate their test build directories, or use test groups to ensure mutual exclusion. Closing as this isn't a nextest issue.
