### ISSUE TITLE
Incorrect pluralization in test output

### ISSUE THREAD

**Issue by Basicprogrammer10** [nextest-rs/nextest#880]
When running nextest on a binary with a single test / binary, it prints lines with incorrect pluralization. It says `1 tests across 1 binaries` and `1 tests run` when it should say `1 test across 1 binary` and `1 test run`.

```
cargo nextest run
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
    Starting 1 tests across 1 binaries
        PASS [   0.013s] tmp::bin/tmp test::test
------------
     Summary [   0.015s] 1 tests run: 1 passed, 0 skipped
```

**Comment by sunshowers** [comment]
Thanks! I agree that this would be good.
