### ISSUE TITLE
Is there a way to repeat a test in case it is unstable until it fails?

### ISSUE THREAD

**Issue by nstinus** [nextest-rs/nextest#882]
I have a test that fails sometimes. --retries for flaky tests is designed to try until it *succeeds* and then the outcome is a success. In my case, I'd like to retry until it *fails*. Is there a way to do that?

**Comment by mati865** [comment]
It would be also useful for checking tests stability.
Consider scenario where you have many tests with tight timing and would like to know whether they are stable. Ofc it can be achieved with shell loop that runs test for defined amount of tries but having that available in tests runner has more possibilities like printing summary of which tests failed and how many times.
