### ISSUE TITLE
feat: Support custom targets

### ISSUE THREAD

**Issue by NobodyXu** [nextest-rs/nextest#887]
Progress:

- [x] Add support for custom targets to target-spec (https://github.com/guppy-rs/guppy/pull/74)
- [x] Looser triple validation (https://github.com/guppy-rs/guppy/commit/738a0c8cb995ddc32be01ffe9a32724f36bf280d)
- [x] Release new target-spec version
- [x] Release new target-spec-miette version
- [x] Release new guppy version
- [x] Update nextest-runner with support: https://github.com/nextest-rs/nextest/pull/891
  - [x] Add support for custom targets as `--target`, `CARGO_BUILD_TARGET`, `build.target` etc (in @sunshowers's local clone) -- includes both directly specified targets and `RUST_TARGET_PATH`.
  - [x] Add tests (mostly done, just need to add tests for `RUST_TARGET_PATH`).
  - [x] ~~Add support for resolving custom targets in `platform` overrides~~ (done in a different manner via https://github.com/guppy-rs/guppy/commit/738a0c8cb995ddc32be01ffe9a32724f36bf280d)
- [x] Publish new nextest-runner version

> Hmm, is nextest not handling custom targets correctly? In addition to the following warning, all dependencies are recompiled when doctest is built.
> 
> ```
> warning: could not determine target triple: error deserializing target triple from --target option
> caused by: unknown platform triple
> caused by: unknown triple string: target-specs/i686-unknown-linux-gnu.json
> caused by: Unrecognized architecture: target
> ```
> 
> https://github.com/tokio-rs/tokio/actions/runs/5244982846/jobs/9472222567#step:7:1274
> 
> Although it probably wouldn't be difficult for nextest to add support for custom targets (probably basically just porting the logic around [this](https://github.com/taiki-e/cargo-config2/blob/c7a341139d68c32c25be827ddaa543f1512fbe94/src/resolve.rs#L487-L505) to [nextest-runner](https://github.com/nextest-rs/nextest/blob/c6d1b98c2bcb7cbfc8cdfd6eda386ea12ba88e4a/nextest-runner/src/cargo_config/target_triple.rs)).

_Originally posted by @taiki-e in https://github.com/tokio-rs/tokio/issues/5691#issuecomment-1587999784_

**Comment by sunshowers** [comment]
Yes, nextest doesn't currently support custom targets. I'd have to add support for them to target-spec, because nextest does some evaluation of targets for [per-test overrides](https://nexte.st/book/per-test-overrides.html). It's just some busy work, probably 1-2 days.

**Comment by sunshowers** [comment]
This is mostly done code-wise, just need to get new versions of various libraries uploaded.

**Comment by sunshowers** [comment]
I was close to releasing a version of nextest today, but realized that I wanted to do target validation somewhat differently. https://github.com/guppy-rs/guppy/commit/738a0c8cb995ddc32be01ffe9a32724f36bf280d has the new approach, and my hope is to get a new version of nextest out by this weekend.

**Comment by sunshowers** [comment]
(I think I'd like to spend some more time thinking about that change before fully committing to it.)

**Comment by sunshowers** [comment]
@NobodyXu finished this up, should be out as cargo-nextest 0.9.54 within the next 20-30 minutes.

**Comment by NobodyXu** [comment]
Thank you @sunshowers !
