### ISSUE TITLE
Print statements cause creation of test list to fail.

### ISSUE THREAD

**Issue by icmccorm** [nextest-rs/nextest#889]
Print statements issued from files in a root `test` directory seem to interfere with nextest's method for building the test list. When running `cargo nextest run` for [curl-rust](https://github.com/alexcrichton/curl-rust.git), I see the following error:
```
error: creating test list failed

Caused by:
  for `curl::atexit`, line 'Finishing...' did not end with the string ': test' or ': benchmark'
full output:
Finishing...
```

The output `Finishing...` occurs due to the entrypoint in [tests/atexit.rs](https://github.com/alexcrichton/curl-rust/blob/main/tests/atexit.rs), which prints before terminating:
```
fn main() {
    curl::init();
    hook();
    unsafe {
        libc::atexit(hook);
    }
    //println!("Finishing...")
}
```
Commenting out the print statement fixes the issue. This is happening on my M1 Macbook Pro, and I've seen this when using both the prebuilt binary and when building from source.

**Comment by sunshowers** [comment]
Thanks for the report! It looks like that test uses a custom test harness: https://github.com/alexcrichton/curl-rust/blob/main/Cargo.toml#L58-L60

Nextest requires that custom test harnesses obey a specific protocol, and this is documented explicitly here: https://nexte.st/book/custom-test-harnesses.html#manually-implementing-a-test-harness

I'd recommend porting the test over to using libtest-mimic, which obeys this protocol.
