### ISSUE TITLE
Add a way to include custom properties into junit report

### ISSUE THREAD

**Issue by AzHicham** [nextest-rs/nextest#897]
Hello, 

I would like to know if it is possible to include custom properties into junit report for each test ?

This could be great in order to mimic functionalities provided by [pytest-jira-xray ](https://pypi.org/project/pytest-jira-xray/). 

Thanks

**Comment by skycoop** [comment]
I would love to see this added as well. It would be extremely useful to be able to include commonly used properties like steps and test metadata.

**Comment by sunshowers** [comment]
This should be out within the next 5 minutes as quick-junit 0.3.3. Thanks everyone!
