### ISSUE TITLE
Support Cargo's `--timings` flag

### ISSUE THREAD

**Issue by cwfitzgerald** [nextest-rs/nextest#903]
Thanks for this amazing tool!

Cargo now supports calling `--timings[=<fmt>]` to generate build timing issues and there doesn't seem to be a way to add that flag to rustup right now.

**Comment by cwfitzgerald** [comment]
Thanks!

**Comment by sunshowers** [comment]
This is out as part of cargo-nextest 0.9.55, out in the next 10 minutes or so.
